# Generated by Django 5.0 on 2023-12-11 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='emial',
            new_name='email',
        ),
    ]
